name: CraftEssence
main: me.furt.CraftEssence.CraftEssence
version: 1.0
author: furt
description: A general plugin with all commands from hMod
commands:
  tp:
    description: Teleport to a player
    usage: |
           /<command> [player]
  tphere:
    description: Teleport a player to you
    usage: |
           /<command> [player]
  give:
    description: Gives items to a player
    usage: |
           Usage: /<command> [player] [item] [amount]
  item:
    description: Gives items to yourself
    usage: |
           Usage: /<command> [item] [amount]
  spawn:
    description: Teleports player to spawn area
    usage: |
           /<command>
  setspawn:
    description: Set the world spawn point
    usage: |
           /<command>
  home:
    description: Teleports player to home location
    usage: |
           Usage: /<command>
  sethome:
    description: Sets player home location
    usage: |
           /<command>
  clearinventory:
    description: Removes all items from players inventory
    usage: |
           Usage: /<command> [player]
  warp:
    description: Teleports to desired warp location
    usage: |
           Usage: /<command> [warpname]
  setwarp:
    description: Creates a warp with desired name
    usage: |
           Usage: /<command> [warpname]
  broadcast:
    description: Sends a server message to everyone online
    usage: |
           Usage: /<command> [message]
  support:
    description: Sends a msg to all admins online
    usage: |
           /<command> [msg]
  mail:
    description: Send messages to online/offline players
    usage: |
           Usage: /<command> [read:send:delete]
  kill:
    description: Kill a player, all, or yourself
    usage: |
           Usage: /<command> [player/*]
  time:
    description: Sets time day/night
    usage: |
           Usage: /<command> [world] [day:night]
  me:
    description: A emote system
    usage: |
           Usage: /<command> [msg]
  msg:
    description: Sends private messages to players
    usage: |
           /<command> [msg]
  jump:
    description: Aim at a location and use command to teleport there
    usage: |
           Usage: /<command>
  top:
    description: Teleports you at the most highest block above you
    usage: |
           /<command>
  ban:
    description: Bans a player from the server
    usage: |
           Usage: /<command> [player] [reason]
  pardon:
    description: Removes a player from the banned list
    usage: |
           /<command> [player]
  compass:
    description: Shows what direction you are facing
    usage: |
           Usage: /<command>
  motd:
    description: Displays the message of the day
    usage: |
           Usage: /<command>
  playerlist:
    description: Shows players that are online
    usage: |
           /<command>
  god:
    description: Enables/Disable invincibility
    usage: |
           Usage: /<command> [player]
  heal:
    description: Heal yourself or another player
    usage: |
           Usage: /<command> [player]
  kick:
    description: Kick a player or all players
    usage: |
           Usage: /<command> [player/*]
  kit:
    description: A package of items
    usage: |
           Usage: /<command> [kitname]