name: CraftEssence
main: me.furt.CraftEssence.CraftEssence
version: 3.0
author: furt
database: true
description: A general plugin with all basic commands needed.
commands:
  reply:
    aliases:
      - r
    description: Reply to last player that has /msg you
    usage: |
           /<command> [message]
  afk:
    description: Flags the player as afk
    usage: |
           /<command>
  tp:
    description: Teleport to a player
    usage: |
           /<command> [player]
  tphere:
    aliases:
      - tph
    description: Teleport a player to you
    usage: |
           /<command> [player]
           /<command> [playerA] [playerB]
  give:
    aliases:
      - g
    description: Gives items to a player
    usage: |
           /<command> [player] [item] [amount]
  item:
    aliases:
      - i
    description: Gives items to yourself
    usage: |
           /<command> [item] [amount]
  spawnmob:
    aliases:
      - sm
    description: Spawns a mob by player
    usage: |
           /<command> [creature] [amount]
  spawn:
    description: Teleports player to spawn area
    usage: |
           /<command>
  setspawn:
    description: Set the world spawn point
    usage: |
           /<command>
  home:
    description: Teleports player to home location and can invite players to your home
    usage: |
           /<command>
           /<command> invite [player]
           /<command> accept
  sethome:
    description: Sets player home location
    usage: |
           /<command>
  clearinventory:
    aliases:
      - clear
    description: Removes all items from players inventory
    usage: |
           /<command> [player]
  warp:
    description: Teleports to desired warp location
    usage: |
           /<command> [warpname]
  setwarp:
    description: Creates a warp with desired name
    usage: |
           /<command> [warpname]
  broadcast:
    description: Sends a server message to everyone online
    usage: |
           /<command> [message]
  support:
    description: Sends a msg to all admins online
    usage: |
           /<command> [msg]
  mail:
    description: Send messages to online/offline players
    usage: |
           /<command> [read:send:delete]
  kill:
    description: Kill a player, all, or yourself
    usage: |
           /<command> [player/*]
  time:
    description: Sets time day/night
    usage: |
           /<command> [day:night] <world>
  me:
    description: A emote system
    usage: |
           /<command> [msg]
  msg:
    description: Sends private messages to players
    usage: |
           /<command> [msg]
  jump:
    aliases:
      - j
    description: Aim at a location and use command to teleport there
    usage: |
           /<command>
  top:
    description: Teleports you at the most highest block above you
    usage: |
           /<command>
  ban:
    description: Bans a player from the server
    usage: |
           /<command> [player] [reason]
  banip:
   aliases:
     - ban-ip
   description: Bans a player from the server by ip
   usage: |
          /<command> [player]
  pardon:
    description: Removes a player from the banned list
    usage: |
           /<command> [player]
  compass:
    description: Shows what direction you are facing
    usage: |
           /<command>
  motd:
    description: Displays the message of the day
    usage: |
           /<command>
  playerlist:
    aliases:
      - list
    description: Shows players that are online
    usage: |
           /<command>
  heal:
    description: Heal yourself or another player
    usage: |
           /<command> [player]
  kick:
    description: Kick a player or all players
    usage: |
           /<command> [player/*]
  kit:
    description: A package of items
    usage: |
           /<command> [kitname]
  worldlist:
    description: Lists all loaded worlds
    usage: |
           /<command>
  mute:
    description: Mutes player so that they cannot talk in chat
    usage: |
           /<command> [player]
  vote:
    description: Players are able to vote on different things
    usage: |
           /<command> [day:night:kick] [world:player]
  who:
    description: Displays player stats
    usage: |
           /<command> [player]
  ceuser:
    description: Allows a user to change various player settings
    usage: |
           /<command> [player] rename [name]
  gamemode:
    aliases:
      - gm
    description: Shows players that are online
    usage: |
           /<command> [player] [mode]
           /<command> [mode]
  hunger:
    description: Replenishes your hunger bar
    usage: |
           /<command>
           /<command> [player]
  weather:
    description: Change weather to rainy, sunny, or thundering
    usage: |
           /<command> [sunny:rainy:thunder]